### ISSUE TITLE
[PE-D] Find command not being case sensitive in its output 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-2/tp#178] opened 2021-10-30 15:49 UTC
![image.png](https://raw.githubusercontent.com/MAZJ124/ped/master/files/1fca2cb1-c433-4686-8d5e-da16501cad75.png)  
Find command does not display the upper case letters in user names, while when adding users, identical spelling names with upper and lower cases are treated separately. This might cause confusion to users when they try to find a specific user(as shown in the picture).

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: MAZJ124/ped#4

**Comment by andrewtkh1** [comment] 2021-11-05 06:03
Duplicate of #197

**Closed by andrewtkh1** 2021-11-05 06:03 UTC
