### ISSUE TITLE
[PE-D] Missing feature mentioned in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-2/tp#196] opened 2021-10-30 17:45 UTC
Team mentioned that users can specify any special requirements but no instructions were provided anywhere. I feel dietary restrictions are important(e.g. Buddhist, Muslim diets)

![image.png](https://raw.githubusercontent.com/irvinseet/ped/main/files/885316ff-03bd-45f9-8535-4daa6c66f3d6.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: irvinseet/ped#5

**Comment by andrewtkh1** [comment] 2021-11-05 06:04
Duplicate of #199

**Closed by andrewtkh1** 2021-11-05 06:04 UTC
