### ISSUE TITLE
[PE-D] Same name but treated separately when adding

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-2/tp#187] opened 2021-10-30 16:46 UTC
![image.png](https://raw.githubusercontent.com/powzx/ped/main/files/869e7346-2a36-4538-a6ce-d5f76648a30c.png)

A suggestion is to consider names as case-insensitive strings?

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: powzx/ped#3

**Comment by andrewtkh1** [comment] 2021-11-05 06:01
Duplicate of #192

**Closed** 2021-11-05 06:02 UTC
